theme: jekyll-theme-minimal
title: Jiying Li
description: Welcome to my website. I am a limnologist/oceanographer who study biogeochemistry of lakes and oceans. Here you can learn and follow updates about my research, teaching, and publications. 
