theme: jekyll-theme-minimal
title: Jiying Li
logo: /master/Jiying.png
description: Welcome to my website. I am a limnologist/oceanographer who study geochemistry of lakes and oceans. Here you can learn and follow updates about my research, teaching, and publications. 
