theme: jekyll-theme-minimal
description: Welcome to the Aquatic Biogeochemistry Laboratory at the Hong Kong University of Science and Technology! We study the exchange and transformation of elements in lakes and oceans.
