theme: jekyll-theme-minimal
google_analytics: UA-172953179-1

# Site Settings
title                    : "Aquatic geochem @ HKUST"
title_separator          : "-"
name                     : &name "Jiying Li"
description: Welcome to our website. We study the exchange and transformation of elements in lakes and oceans. We are at the Department of Ocean Science, Hong Kong University of Science and Technology. 
url                      : https://jiyingli.github.io 

  
